### ISSUE TITLE
several "assert" statements in the code

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.learn.boosting#1]
it appears that the C++ code contains several ``assert`` statements, which will either be ignored, i.e., when compiled with ``-DNDEBUG`` (the default!!) or raise C-Style exceptions, which cannot be caught by the Python bindings.

Is it possible to change these asserts into proper tests that raise exceptions?

**Comment by tiagofrepereira2012** [comment]
Hey @siebenkopf , are you still on this one :-) ?

Cheers

**Comment by siebenkopf** [comment]
I am not sure that I'll find the time to work on that any more. Maybe when I am at UCCS.

**Comment by siebenkopf** [comment]
Fixed with https://github.com/bioidiap/bob.learn.boosting/commit/c1c7b4ef50c533609a494a5552dbfa56f6d29f50
